# Generated by Django 4.1 on 2022-08-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='x',
        ),
    ]
