# Generated by Django 4.1 on 2022-08-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
        ('inventory', '0004_remove_inventory_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='group',
        ),
        migrations.CreateModel(
            name='CategoryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='group',
            field=models.ManyToManyField(through='inventory.CategoryInventory', to='category.category'),
        ),
        migrations.AddConstraint(
            model_name='categoryinventory',
            constraint=models.UniqueConstraint(fields=('category', 'inventory'), name='unique_category_inventory'),
        ),
    ]
