# Generated by Django 4.1 on 2022-08-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_storeinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
