# Generated by Django 4.1 on 2022-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('inventory', '0009_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ManyToManyField(blank=True, null=True, related_name='inventories_store', through='inventory.StoreInventory', to='store.store', verbose_name='Tienda'),
        ),
    ]
