# Generated by Django 4.1 on 2022-08-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
        ('inventory', '0013_alter_inventory_name_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='category.category', verbose_name='Grupo'),
        ),
    ]
