# Generated by Django 4.1 on 2022-08-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('inventory', '0014_alter_inventory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
