# Generated by Django 4.1 on 2022-08-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0013_alter_inventory_name_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('motion', models.CharField(choices=[('tarma', 'tarma'), ('la-merced', 'la-merced'), ('huancayo', 'huancayo'), ('pichanaqui', 'pichanaqui'), ('fabrica', 'fabrica'), ('venta', 'venta')], default='venta', max_length=10)),
                ('inventory_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.storeinventory')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['-created_at'],
            },
        ),
    ]
