# Generated by Django 4.1 on 2022-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='motion',
            field=models.CharField(choices=[('tarma', 'Tarma'), ('la-merced', 'La Merced'), ('huancayo', 'Huancayo'), ('pichanaqui', 'Pichanaqui'), ('fabrica', 'Fabrica'), ('venta', 'Venta')], default='venta', max_length=10),
        ),
    ]
