# Generated by Django 4.1 on 2022-08-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_motion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='motion',
            field=models.CharField(choices=[('Tarma', 'Tarma'), ('La-merced', 'La Merced'), ('Huancayo', 'Huancayo'), ('Pichanaqui', 'Pichanaqui'), ('Fabrica', 'Fabrica'), ('Venta', 'Venta')], default='venta', max_length=10),
        ),
    ]
